// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoUCEhfVTbUOss-C_ZljT1pX6zvI2BHFk',
    appId: '1:989617007030:web:c09d8b26985723e68c7917',
    messagingSenderId: '989617007030',
    projectId: 'testing-58d8f',
    authDomain: 'testing-58d8f.firebaseapp.com',
    storageBucket: 'testing-58d8f.appspot.com',
    measurementId: 'G-K5GMSLGKEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBkV43EpS-VahdTx5aDNhnbXH03kalH00',
    appId: '1:989617007030:android:4bcd6f39581df53b8c7917',
    messagingSenderId: '989617007030',
    projectId: 'testing-58d8f',
    storageBucket: 'testing-58d8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdX_JpKKLr99RuaTZ1A0MNTvWKOjUi3mw',
    appId: '1:989617007030:ios:3e296559f45b24898c7917',
    messagingSenderId: '989617007030',
    projectId: 'testing-58d8f',
    storageBucket: 'testing-58d8f.appspot.com',
    iosBundleId: 'com.example.planto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdX_JpKKLr99RuaTZ1A0MNTvWKOjUi3mw',
    appId: '1:989617007030:ios:2d25a52eda1dfe6a8c7917',
    messagingSenderId: '989617007030',
    projectId: 'testing-58d8f',
    storageBucket: 'testing-58d8f.appspot.com',
    iosBundleId: 'com.example.planto.RunnerTests',
  );
}
